#!/bin/bash

# =============================================================
# LeadEnforce - One-Command VPS Deploy
# =============================================================
# Usage: curl -fsSL https://raw.githubusercontent.com/varuoog755-creator/leadandforce/main/deploy-vps.sh | bash
# =============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║      🚀 LeadEnforce - VPS Auto-Deploy           ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# ---- Step 1: System Update ----
echo -e "${GREEN}[1/7]${NC} Updating system packages..."
sudo apt update -y -qq && sudo apt upgrade -y -qq
sudo apt install -y -qq git curl

# ---- Step 2: Install Docker ----
echo -e "${GREEN}[2/7]${NC} Installing Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker $USER
    echo -e "  ${GREEN}✔${NC} Docker installed"
else
    echo -e "  ${GREEN}✔${NC} Docker already installed"
fi

# ---- Step 3: Install Docker Compose ----
echo -e "${GREEN}[3/7]${NC} Installing Docker Compose..."
if ! docker compose version &> /dev/null; then
    sudo apt install -y -qq docker-compose-plugin 2>/dev/null || {
        COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)
        sudo curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    }
    echo -e "  ${GREEN}✔${NC} Docker Compose installed"
else
    echo -e "  ${GREEN}✔${NC} Docker Compose already installed"
fi

# ---- Step 4: Clone Repo ----
echo -e "${GREEN}[4/7]${NC} Cloning repository..."
APP_DIR="/opt/leadenforce"
sudo mkdir -p "$APP_DIR"
sudo chown $USER:$USER "$APP_DIR"

if [ -d "$APP_DIR/.git" ]; then
    cd "$APP_DIR"
    git pull origin main
    echo -e "  ${GREEN}✔${NC} Repository updated"
else
    git clone https://github.com/varuoog755-creator/leadandforce.git "$APP_DIR"
    cd "$APP_DIR"
    echo -e "  ${GREEN}✔${NC} Repository cloned"
fi

# ---- Step 5: Auto-detect IP & Generate .env ----
echo -e "${GREEN}[5/7]${NC} Configuring environment..."
VPS_IP=$(curl -s ifconfig.me 2>/dev/null || curl -s icanhazip.com 2>/dev/null || echo "localhost")

if [ ! -f .env ]; then
    # Generate random JWT secret
    JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 64)
    POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 32)

    cat > .env <<EOF
# Auto-generated by deploy-vps.sh on $(date)
VPS_IP=${VPS_IP}

# PostgreSQL
POSTGRES_DB=leadenforce
POSTGRES_USER=leadenforce_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# JWT
JWT_SECRET=${JWT_SECRET}

# Firebase (fill in from Firebase Console > Project Settings)
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=
EOF
    echo -e "  ${GREEN}✔${NC} .env created with auto-generated secrets"
    echo -e "  ${YELLOW}⚠  Add Firebase keys later: nano $APP_DIR/.env${NC}"
else
    # Update VPS_IP if it changed
    sed -i "s/^VPS_IP=.*/VPS_IP=${VPS_IP}/" .env
    echo -e "  ${GREEN}✔${NC} .env exists (VPS_IP updated to ${VPS_IP})"
fi

# ---- Step 6: Build & Start ----
echo -e "${GREEN}[6/7]${NC} Building and starting containers..."
docker compose down 2>/dev/null || true
docker compose build --no-cache
docker compose up -d

# ---- Step 7: Wait & Verify ----
echo -e "${GREEN}[7/7]${NC} Waiting for services to start..."
sleep 15

# Health check
BACKEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3001/health 2>/dev/null || echo "000")
FRONTEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000 2>/dev/null || echo "000")

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║            📊 Deployment Status                 ║${NC}"
echo -e "${CYAN}╠══════════════════════════════════════════════════╣${NC}"

if [ "$BACKEND_STATUS" = "200" ]; then
    echo -e "${CYAN}║${NC} Backend API:  ${GREEN}✔ Running${NC}                         ${CYAN}║${NC}"
else
    echo -e "${CYAN}║${NC} Backend API:  ${RED}✘ Starting (may take a moment)${NC}   ${CYAN}║${NC}"
fi

if [ "$FRONTEND_STATUS" = "200" ]; then
    echo -e "${CYAN}║${NC} Frontend:     ${GREEN}✔ Running${NC}                         ${CYAN}║${NC}"
else
    echo -e "${CYAN}║${NC} Frontend:     ${YELLOW}⏳ Building (wait 1-2 min)${NC}       ${CYAN}║${NC}"
fi

echo -e "${CYAN}╠══════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║${NC}  🌐 App:     ${GREEN}http://${VPS_IP}:3000${NC}"
echo -e "${CYAN}║${NC}  🔧 API:     ${GREEN}http://${VPS_IP}:3001${NC}"
echo -e "${CYAN}║${NC}  📁 Files:   ${GREEN}${APP_DIR}${NC}"
echo -e "${CYAN}╠══════════════════════════════════════════════════╣${NC}"
echo -e "${CYAN}║${NC}  ${YELLOW}Commands:${NC}                                      ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   Logs:     docker compose logs -f             ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   Stop:     docker compose down                ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   Update:   git pull && docker compose up -d   ${CYAN}║${NC}"
echo -e "${CYAN}║${NC}   Config:   nano ${APP_DIR}/.env          ${CYAN}║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
